### ISSUE TITLE
More Cert Creation Parameters

### ISSUE THREAD

**Issue by afroDC** [GluuFederation/docker-config-init#1]
https://github.com/GluuFederation/docker-config-init/blob/3.1.2/entrypoint.py#L419

Cert generation needs to match the standard requirements for Gluu Server. 

Country, State/Province/Territory and City

**Comment by iromli** [comment]
Email and Organization already supported in `config-init`.

**Comment by afroDC** [comment]
Edited

**Comment by iromli** [comment]
This feature has been merged to `3.1.2` branch.
