### ISSUE TITLE
Import config and secret from CE

### ISSUE THREAD

**Issue by iromli** [GluuFederation/docker-config-init#10]
A feature to import config from existing CE will be useful for existing users who want to migrate to CN edition.

**Comment by iromli** [comment]
We didn't see any required feature for this one at the moment

**Comment by iromli** [comment]
Re-opened to address usecase where users need to migrate from CE to CN Edition

**Comment by iromli** [comment]
The work-in-progress code is on [ce-to-cn branch](https://github.com/GluuFederation/docker-config-init/tree/ce-to-cn)

**Comment by moabu** [comment]
Merged in 4.3
https://github.com/GluuFederation/docker-config-init/commit/57398ea55826350d1b6cdcb0cf22b71c3f25b4cd

**Comment by iromli** [comment]
Re-opened to track progress/issue/etc where we need add support migrating config and secret from upcoming Spanner and SQL persistence.
