### ISSUE TITLE
Deployment failed when City Name contains quotation

### ISSUE THREAD

**Issue by xionglingfeng** [GluuFederation/docker-config-init#13]
The deployment failed as below when the city name contains quotation (e.g. `St. John's`)

> Continue with the above settings? [Y/n]
> [I] Deploying containers
> Creating nginx        ... done
> Creating oxshibboleth ... done
> Creating oxauth       ... done
> Creating ldap         ... done
> Creating oxtrust      ... done
> Creating oxpassport   ... done
> Creating consul       ... done
> Creating registrator  ... done
> [I] Generating configuration for the first time; this may take a moment
> Config backend is ready.
> Generating config.
>   adding new key 'encoded_salt'
>   adding new key 'orgName'
>   adding new key 'country_code'
>   adding new key 'state'
>   adding new key 'city'
>   adding new key 'hostname'
>   adding new key 'admin_email'
>   adding new key 'default_openid_jks_dn_name'
>   adding new key 'pairwiseCalculationKey'
>   adding new key 'pairwiseCalculationSalt'
>   adding new key 'jetty_base'
>   adding new key 'ldap_init_host'
>   adding new key 'ldap_init_port'
>   adding new key 'ldap_port'
>   adding new key 'ldaps_port'
>   adding new key 'ldap_truststore_pass'
>   adding new key 'ldap_type'
>   adding new key 'ldap_binddn'
>   adding new key 'ldap_site_binddn'
>   adding new key 'ldapTrustStoreFn'
> Traceback (most recent call last):
>   File "./scripts/entrypoint.py", line 965, in <module>
>     cli()
>   File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
>     rv = self.invoke(ctx)
>   File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
>     return callback(*args, **kwargs)
>   File "./scripts/entrypoint.py", line 859, in generate
>     inum_appliance)
>   File "./scripts/entrypoint.py", line 233, in generate_config
>     cfg["city"],
>   File "./scripts/entrypoint.py", line 728, in generate_ssl_certkey
>     "-subj /C='{}'/ST='{}'/L='{}'/O='{}'/CN='{}'/emailAddress='{}'".format(country_code, state, city, org_name, domain, email),
>   File "./scripts/entrypoint.py", line 103, in exec_cmd
>     args = shlex.split(cmd)
>   File "/usr/lib/python2.7/shlex.py", line 279, in split
>     return list(lex)
>   File "/usr/lib/python2.7/shlex.py", line 269, in next
>     token = self.get_token()
>   File "/usr/lib/python2.7/shlex.py", line 96, in get_token
>     raw = self.read_token()
>   File "/usr/lib/python2.7/shlex.py", line 172, in read_token
>     raise ValueError, "No closing quotation"
> ValueError: No closing quotation
>

**Comment by iromli** [comment]
@xionglingfeng thanks for the report, I will take a look

**Comment by iromli** [comment]
@xionglingfeng the `gluufederation/config-init` image has been upgraded to `3.1.4_02`. You can reference any script/command to use `gluufederation/config-init:3.1.4_02` instead.

Let me know if it works for you.

**Comment by iromli** [comment]
Closing this issue, feel free to reopen if the issue persists.
